CREATE TABLE IF not EXISTS users (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    UserName char(20) UNIQUE NOT NULL,
    Email char(50) UNIQUE NOT NULL,
    Password char(20),
    Created_At DATE NOT NULL,
    Session TEXT ,
    Expared_At DATE, 
    AuthType char(10) DEFAULT "normal"
 );
CREATE TABLE IF NOT EXISTS Posts (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Title char(50),
    Content TEXT, 
    DateCreation DATE,
    Image BLOB,
    ID_User INTEGER,
    FOREIGN KEY (ID_User) REFERENCES users(ID) ON DELETE CASCADE ON UPDATE CASCADE 
);

CREATE TABLE IF NOT EXISTS Category(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name_Category varchar(20) UNIQUE
);

CREATE TABLE IF NOT EXISTS PostCategory(
    ID_Post INTEGER,
    ID_Category INTEGER,
    PRIMARY KEY (ID_Post, ID_Category),
    FOREIGN KEY (ID_Post) REFERENCES Posts(ID) ON DELETE CASCADE ON UPDATE CASCADE, 
    FOREIGN KEY (ID_Category) REFERENCES Category(ID) ON DELETE CASCADE ON UPDATE CASCADE 
);


CREATE TABLE IF NOT EXISTS Post_Like(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    status varchar(10),
    ID_User INTEGER,   
    ID_Post INTEGER,
    FOREIGN KEY (ID_User) REFERENCES users(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_Post) REFERENCES Posts(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Comment(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Content TEXT,
    DateCreation DATE,
    ID_User INTEGER,    
    ID_Post INTEGER,
    FOREIGN KEY (ID_User) REFERENCES users(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_Post) REFERENCES Posts(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Comment_Like(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    status varchar(10),
    ID_User INTEGER,    
    ID_Comment INTEGER,
    FOREIGN KEY (ID_User) REFERENCES users(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_Comment) REFERENCES Comment(ID) ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT OR IGNORE INTO Category (Name_Category) VALUES ('Coding');
INSERT OR IGNORE INTO Category (Name_Category) VALUES ('Innovation');
INSERT OR IGNORE INTO Category (Name_Category) VALUES ('Betcoin');
INSERT OR IGNORE INTO Category (Name_Category) VALUES ('kids');
INSERT OR IGNORE INTO Category (Name_Category) VALUES ('movie');
INSERT OR IGNORE INTO Category (Name_Category) VALUES ('sport');
INSERT OR IGNORE INTO Category (Name_Category) VALUES ('food');